# .github/workflows/docker.yml
name: Docker Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Kuznetsov-Diplom
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/kuznetsov-diplom/dasha:latest
            ghcr.io/kuznetsov-diplom/dasha:sha-${{ github.sha }}
